In [71]:
import pandas as pd
import numpy as np


In [72]:
df = pd.read_csv("spam.csv")

In [73]:
df.head()

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [75]:
df.Category.value_counts()

,count
Category,
ham,4825
spam,747


In [78]:
df['spam'] = df['Category'].apply(lambda x : 1 if x=='spam' else 0)

In [79]:
df.head()

,Category,Message,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [80]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [81]:
X_train.shape

(4457,)

In [82]:
type(X_train)

pandas.core.series.Series

In [84]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)

In [85]:

X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [91]:
v.get_feature_names_out()[4869]

'offers'

In [87]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [90]:
np.where(X_train_np[0]!=0)

(array([ 528,  963, 1608, 2067, 2263, 2960, 2995, 3090, 3206, 3488, 4655,
        4766, 4841, 4861, 4869, 5223, 5302, 5313, 5674, 5696, 6747, 6810,
        6891, 7196, 7499, 7660]),)

In [93]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [94]:
X_test_cv = v.transform(X_test)

In [95]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       968
           1       0.99      0.93      0.96       147

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [101]:
emails = [
    'How are you Vansh, are you up for a football game tomorrow?',
    'Upto 30% discount on parking, exclusive offer just for you. Dont miss this reward',
]


emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [103]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [105]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [108]:
pred = clf.predict(X_test)

In [110]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       968
           1       0.99      0.93      0.96       147

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.98      1115
weighted avg       0.99      0.99      0.99      1115

